### ISSUE TITLE
Use YAML instead of JSON for database entries

### ISSUE THREAD

**Issue by AdrienWehrle** [APECS-Earth-Observation/Polar-EO-Database#31]
- `JSON` is nice, simple and low level, and for that latter reason it is data-only and therefore comments of the form `//…` or `/*…*/` are not allowed. Which is a problem for us because we want the community to understand the entries and potentially contribute! 

- [`YAML`](https://circleci.com/blog/what-is-yaml-a-beginner-s-guide/#:~:text=YAML%20is%20a%20digestible%20data,that%20JSON%20can%20and%20more.) is also nice and simple, but even more human readable than `JSON`. Comments are allowed, and there are no embedded brackets that can be scary for potential contributors not used to it. It is used a lot for metadata, an example [here](https://github.com/AdrienWehrle/earthspy/blob/main/meta.yaml). 

For those reasons, I think we should move to `YAML`. This sounds like a big thing, but is simply about saving data in another format (I can implement the change if we take that decision). 

Also, I stepped back from #30 and closed it, as we first need to take that decision, then we can work again on the template in the format we'll choose! :smiley:

**Comment by Azamattf** [comment]
@AdrienWehrle Do you see any drawbacks of moving to YAML?

**Comment by AdrienWehrle** [comment]
> @AdrienWehrle Do you see any drawbacks of moving to YAML?

JSON is simpler and more widespread but YAML is **very** close behind, so I don't see any real drawback here.

**Comment by AdrienWehrle** [comment]
Following the monthly meeting of the APECS Remote Sensing Project Group, we decided to migrate to YAML! :tada:
